export {Home} from "./Home"
export {Categories} from "./Categories"
export {Result} from "./Result"
export {LeaderBoard} from "./LeaderBoard"
export {Login} from "./Login"
export {Signup} from "./Signup"